apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-w50r
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-w50r
    app.kubernetes.io/part-of: ci10t-777-0020-app
  name: devfile-sample-w50r
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-w50r
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-w50r
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-777-0020-tenant/ci10t-777-0020-app/devfile-sample-w50r@sha256:ba05d1a76c00aa371ead4ae21aa99cbcc2ccb40d193313c5b7a1082def66da18
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
